sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t foobar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true foobar/docker-react npm run test
